<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.1" os="" host="BLSSTGATST2"><DocLocation><![CDATA[H:\HPA_Test\Test Resources_Claims\Scripts\Claims Smoke Test\TC_001_CLAIMS_REGTESTSUITE]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[TC_001_CLAIMS_REGTESTSUITE]]></DName>
<Res><![CDATA[Report1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Action rID="T5">
<AName><![CDATA[Action1 [GlobalDriver_Working_Claims]]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[5/12/2022 - 1:21:48]]></Time>
<TimeTick>1652332908</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="9" status="Passed" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="151" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[5/12/2022 - 1:21:50]]></Time>
<TimeTick>1652332910</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="10" status="Passed" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="153" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[5/12/2022 - 1:21:50]]></Time>
<TimeTick>1652332910</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="11" status="Passed" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="154" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[5/12/2022 - 1:21:50]]></Time>
<TimeTick>1652332910</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="155" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA[Test Information]]></Obj>
<Details ><![CDATA[datasheetused:CLAIMS_REGRESSIONSUITE.xlsServer Used:hpasstgaweb1]]></Details>
<Time><![CDATA[5/12/2022 - 1:21:50]]></Time>
<TimeTick>1652332910</TimeTick>
<NodeArgs eType="User" icon="7" nRep="13" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="167" >
<Disp><![CDATA[Test Information]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj ><![CDATA[Find Row No]]></Obj>
<Details ><![CDATA[Row No ofTC_Rebranding_Homepage:12]]></Details>
<Time><![CDATA[5/12/2022 - 1:21:59]]></Time>
<TimeTick>1652332919</TimeTick>
<NodeArgs eType="User" icon="7" nRep="14" status="Passed" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="456" >
<Disp><![CDATA[Find Row No]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj ><![CDATA[Find Row No]]></Obj>
<Details ><![CDATA[Row No ofTC_Rebranding_Homepage_END:17]]></Details>
<Time><![CDATA[5/12/2022 - 1:22:05]]></Time>
<TimeTick>1652332925</TimeTick>
<NodeArgs eType="User" icon="7" nRep="15" status="Passed" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="456" >
<Disp><![CDATA[Find Row No]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[Find Row No]]></Obj>
<Details ><![CDATA[Row No ofLOGOFF:6]]></Details>
<Time><![CDATA[5/12/2022 - 1:22:11]]></Time>
<TimeTick>1652332931</TimeTick>
<NodeArgs eType="User" icon="7" nRep="16" status="Passed" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="456" >
<Disp><![CDATA[Find Row No]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[Find Row No]]></Obj>
<Details ><![CDATA[Row No ofLOGOFF_END:11]]></Details>
<Time><![CDATA[5/12/2022 - 1:22:17]]></Time>
<TimeTick>1652332937</TimeTick>
<NodeArgs eType="User" icon="7" nRep="17" status="Passed" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="456" >
<Disp><![CDATA[Find Row No]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[5/12/2022 - 1:22:25]]></Time>
<TimeTick>1652332945</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Details>
<Time><![CDATA[5/12/2022 - 1:22:25]]></Time>
<TimeTick>1652332945</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" status="Passed" >
<Disp><![CDATA[Run "iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="20" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[Launch application]]></Obj>
<Details ><![CDATA[Application launched successfully:http://hpasstgaweb2.stga.mapshc.com/HPAALL/HPA/Master/Qmain.aspx]]></Details>
<Time><![CDATA[5/12/2022 - 1:22:31]]></Time>
<TimeTick>1652332951</TimeTick>
<NodeArgs eType="User" icon="7" nRep="22" status="Passed" >
<Disp><![CDATA[Launch application]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    1]]></Details>
<Time><![CDATA[5/12/2022 - 1:22:31]]></Time>
<TimeTick>1652332951</TimeTick>
<NodeArgs eType="User" icon="7" nRep="23" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="1625" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    2,Value used:10]]></Details>
<Time><![CDATA[5/12/2022 - 1:22:42]]></Time>
<TimeTick>1652332962</TimeTick>
<NodeArgs eType="User" icon="7" nRep="24" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="1627" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj ><![CDATA[Skip row]]></Obj>
<Details ><![CDATA[You have successfully skipped the row no 1]]></Details>
<Time><![CDATA[5/12/2022 - 1:22:42]]></Time>
<TimeTick>1652332962</TimeTick>
<NodeArgs eType="User" icon="7" nRep="25" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="563" >
<Disp><![CDATA[Skip row]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    4]]></Details>
<Time><![CDATA[5/12/2022 - 1:22:51]]></Time>
<TimeTick>1652332971</TimeTick>
<NodeArgs eType="User" icon="7" nRep="26" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="1625" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Brw_Home_Page]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/12/2022 - 1:22:52]]></Time>
<TimeTick>1652332972</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Pge_QNXT_Home_Page_Reb]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/12/2022 - 1:22:52]]></Time>
<TimeTick>1652332972</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Elm_Name_Home.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/12/2022 - 1:22:52]]></Time>
<TimeTick>1652332972</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="30" >
<Disp><![CDATA[Elm_Name_Home.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[Browser("Brw Home Page").Page("Pge QNXT Home Page Reb").WebElement("Elm Name Home")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Elm_Name_Home.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/12/2022 - 1:22:52]]></Time>
<TimeTick>1652332972</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="32" >
<Disp><![CDATA[Elm_Name_Home.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[Browser("Brw Home Page").Page("Pge QNXT Home Page Reb").WebElement("Elm Name Home")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="29" >
<Disp><![CDATA[Pge_QNXT_Home_Page_Reb]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act2\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[Browser("Brw_Home_Page").Page("Pge_QNXT_Home_Page_Reb")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="28" >
<Disp><![CDATA[Brw_Home_Page]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[24249296]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj ><![CDATA[Name_Home]]></Obj>
<Details ><![CDATA[Succeded at Row No:    13,Value used:Administrator - Home]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:00]]></Time>
<TimeTick>1652332980</TimeTick>
<NodeArgs eType="User" icon="7" nRep="34" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="1627" >
<Disp><![CDATA[Name_Home]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[Excel Value Verification]]></Obj>
<Details ><![CDATA[Value1 Administrator - Home and Value2 Administrator - Home are Same]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:00]]></Time>
<TimeTick>1652332980</TimeTick>
<NodeArgs eType="User" icon="7" nRep="35" status="Passed" >
<Disp><![CDATA[Excel Value Verification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    14,Value used:Administrator - Home;Administrator - Home]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:00]]></Time>
<TimeTick>1652332980</TimeTick>
<NodeArgs eType="User" icon="7" nRep="36" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="1627" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    15]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:06]]></Time>
<TimeTick>1652332986</TimeTick>
<NodeArgs eType="User" icon="7" nRep="37" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="1625" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Brw_Home_Page]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:07]]></Time>
<TimeTick>1652332987</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Pge_QNXT_Home_Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:07]]></Time>
<TimeTick>1652332987</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Lnk_Log_Off.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:07]]></Time>
<TimeTick>1652332987</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="41" >
<Disp><![CDATA[Lnk_Log_Off.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf7.xml]]></Path>
<ASHilite><![CDATA[Browser("Brw Home Page").Page("Pge QNXT Home Page").Link("Lnk Log Off")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Lnk_Log_Off.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:07]]></Time>
<TimeTick>1652332987</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="44" >
<Disp><![CDATA[Lnk_Log_Off.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf8.xml]]></Path>
<ASHilite><![CDATA[Browser("Brw Home Page").Page("Pge QNXT Home Page").Link("Lnk Log Off")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="40" >
<Disp><![CDATA[Pge_QNXT_Home_Page]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act2\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[Browser("Brw_Home_Page").Page("Pge_QNXT_Home_Page")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="39" >
<Disp><![CDATA[Brw_Home_Page]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[24249296]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj ><![CDATA[Log_Off]]></Obj>
<Details ><![CDATA[Succeded at Row No:    6]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:08]]></Time>
<TimeTick>1652332988</TimeTick>
<NodeArgs eType="User" icon="7" nRep="45" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="1625" >
<Disp><![CDATA[Log_Off]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    7,Value used:5]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:14]]></Time>
<TimeTick>1652332994</TimeTick>
<NodeArgs eType="User" icon="7" nRep="46" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="1627" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Win_Logoff]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:14]]></Time>
<TimeTick>1652332994</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Win_Logoff.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:14]]></Time>
<TimeTick>1652332994</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="48" >
<Disp><![CDATA[Win_Logoff.Exist]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf10.xml]]></Path>
<ASHilite><![CDATA[28835862]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Win_Logoff.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:14]]></Time>
<TimeTick>1652332994</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="50" >
<Disp><![CDATA[Win_Logoff.Activate]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf11.xml]]></Path>
<ASHilite><![CDATA[28835862]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Pge_logoff]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:14]]></Time>
<TimeTick>1652332994</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Frm_Logoff]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:14]]></Time>
<TimeTick>1652332994</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Btn_Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:15]]></Time>
<TimeTick>1652332995</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="54" >
<Disp><![CDATA[Btn_Yes.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf14.xml]]></Path>
<ASHilite><![CDATA[Window("Win Logoff").Page("Pge logoff").Frame("Frm Logoff").WebButton("Btn Yes")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Btn_Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:15]]></Time>
<TimeTick>1652332995</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="57" >
<Disp><![CDATA[Btn_Yes.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf15.xml]]></Path>
<ASHilite><![CDATA[Window("Win Logoff").Page("Pge logoff").Frame("Frm Logoff").WebButton("Btn Yes")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="14" nRep="53" >
<Disp><![CDATA[Frm_Logoff]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf13.xml]]></Path>
<ASHilite><![CDATA[Window("Win Logoff").Page("Pge logoff").Frame("Frm Logoff")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="52" >
<Disp><![CDATA[Pge_logoff]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act2\Row0\ssf12.xml]]></Path>
<ASHilite><![CDATA[Window("Win_Logoff").Page("Pge_logoff")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="47" >
<Disp><![CDATA[Win_Logoff]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf9.xml]]></Path>
<ASHilite><![CDATA[28835862]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj ><![CDATA[Yes]]></Obj>
<Details ><![CDATA[Succeded at Row No:    8]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:15]]></Time>
<TimeTick>1652332995</TimeTick>
<NodeArgs eType="User" icon="7" nRep="58" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="1625" >
<Disp><![CDATA[Yes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Brw_Home_Page]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:16]]></Time>
<TimeTick>1652332996</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Brw_Home_Page.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:16]]></Time>
<TimeTick>1652332996</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="60" >
<Disp><![CDATA[Brw_Home_Page.Close]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf17.xml]]></Path>
<ASHilite><![CDATA[24249296]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="59" >
<Disp><![CDATA[Brw_Home_Page]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf16.xml]]></Path>
<ASHilite><![CDATA[24249296]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    9]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:17]]></Time>
<TimeTick>1652332997</TimeTick>
<NodeArgs eType="User" icon="7" nRep="61" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="1625" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA[ScreenshotPath]]></Obj>
<Details ><![CDATA[Path to screenshot on the local drive:H:\HPA_Test\Working\m91\hpasstgaweb1\Screenshots]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:17]]></Time>
<TimeTick>1652332997</TimeTick>
<NodeArgs eType="User" icon="7" nRep="62" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="291" >
<Disp><![CDATA[ScreenshotPath]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj ><![CDATA[Find Row No]]></Obj>
<Details ><![CDATA[Row No ofTC_Rebranding_Administration:18]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:24]]></Time>
<TimeTick>1652333004</TimeTick>
<NodeArgs eType="User" icon="7" nRep="63" status="Passed" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="456" >
<Disp><![CDATA[Find Row No]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA[Find Row No]]></Obj>
<Details ><![CDATA[Row No ofTC_Rebranding_Administration_END:88]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:30]]></Time>
<TimeTick>1652333010</TimeTick>
<NodeArgs eType="User" icon="7" nRep="64" status="Passed" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="456" >
<Disp><![CDATA[Find Row No]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj ><![CDATA[Find Row No]]></Obj>
<Details ><![CDATA[Row No ofLOGOFF:6]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:36]]></Time>
<TimeTick>1652333016</TimeTick>
<NodeArgs eType="User" icon="7" nRep="65" status="Passed" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="456" >
<Disp><![CDATA[Find Row No]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj ><![CDATA[Find Row No]]></Obj>
<Details ><![CDATA[Row No ofLOGOFF_END:11]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:42]]></Time>
<TimeTick>1652333022</TimeTick>
<NodeArgs eType="User" icon="7" nRep="66" status="Passed" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="456" >
<Disp><![CDATA[Find Row No]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:50]]></Time>
<TimeTick>1652333030</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:50]]></Time>
<TimeTick>1652333030</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="70" status="Passed" >
<Disp><![CDATA[Run "iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="69" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj ><![CDATA[Launch application]]></Obj>
<Details ><![CDATA[Application launched successfully:http://hpasstgaweb2.stga.mapshc.com/HPAALL/HPA/Master/Qmain.aspx]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:56]]></Time>
<TimeTick>1652333036</TimeTick>
<NodeArgs eType="User" icon="7" nRep="71" status="Passed" >
<Disp><![CDATA[Launch application]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    1]]></Details>
<Time><![CDATA[5/12/2022 - 1:23:56]]></Time>
<TimeTick>1652333036</TimeTick>
<NodeArgs eType="User" icon="7" nRep="72" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="1625" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    2,Value used:10]]></Details>
<Time><![CDATA[5/12/2022 - 1:24:07]]></Time>
<TimeTick>1652333047</TimeTick>
<NodeArgs eType="User" icon="7" nRep="73" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="1627" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj ><![CDATA[Skip row]]></Obj>
<Details ><![CDATA[You have successfully skipped the row no 1]]></Details>
<Time><![CDATA[5/12/2022 - 1:24:07]]></Time>
<TimeTick>1652333047</TimeTick>
<NodeArgs eType="User" icon="7" nRep="74" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="563" >
<Disp><![CDATA[Skip row]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    4]]></Details>
<Time><![CDATA[5/12/2022 - 1:24:16]]></Time>
<TimeTick>1652333056</TimeTick>
<NodeArgs eType="User" icon="7" nRep="75" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="1625" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    18,Value used:2]]></Details>
<Time><![CDATA[5/12/2022 - 1:24:19]]></Time>
<TimeTick>1652333059</TimeTick>
<NodeArgs eType="User" icon="7" nRep="76" Source="Action1 [GlobalDriver_Working_Claims]" SourceLine="1627" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Brw_Home_Page]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/12/2022 - 1:24:19]]></Time>
<TimeTick>1652333059</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Pge_QNXT_Home_Page_Reb]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/12/2022 - 1:24:19]]></Time>
<TimeTick>1652333059</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Lnk_Claims.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/12/2022 - 1:24:19]]></Time>
<TimeTick>1652333059</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="80" >
<Disp><![CDATA[Lnk_Claims.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf20.xml]]></Path>
<ASHilite><![CDATA[Browser("Brw Home Page").Page("Pge QNXT Home Page Reb").Link("Lnk Claims")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Lnk_Claims.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/12/2022 - 1:24:20]]></Time>
<TimeTick>1652333060</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="83" >
<Disp><![CDATA[Lnk_Claims.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf21.xml]]></Path>
<ASHilite><![CDATA[Browser("Brw Home Page").Page("Pge QNXT Home Page Reb").Link("Lnk Claims")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="79" >
<Disp><![CDATA[Pge_QNXT_Home_Page_Reb]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act2\Row0\ssf19.xml]]></Path>
<ASHilite><![CDATA[Browser("Brw_Home_Page").Page("Pge_QNXT_Home_Page_Reb")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="78" >
<Disp><![CDATA[Brw_Home_Page]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf18.xml]]></Path>