<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.1" os="" host="BLSSTGATST2"><DocLocation><![CDATA[H:\HPA_Test\Test Resources_VUE360\Scripts\VUE360 Smoke Test\TC_01_VUE360_SMOKETESTSUITE]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[TC_01_VUE360_SMOKETESTSUITE]]></DName>
<Res><![CDATA[Report26]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Action rID="T5">
<AName><![CDATA[Action1 [GlobalDriver_Working]]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[5/6/2022 - 2:26:03]]></Time>
<TimeTick>1651818363</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="9" status="Passed" Source="Action1 [GlobalDriver_Working]" SourceLine="151" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[5/6/2022 - 2:26:05]]></Time>
<TimeTick>1651818365</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="10" status="Passed" Source="Action1 [GlobalDriver_Working]" SourceLine="153" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[5/6/2022 - 2:26:05]]></Time>
<TimeTick>1651818365</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="11" status="Passed" Source="Action1 [GlobalDriver_Working]" SourceLine="154" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[5/6/2022 - 2:26:06]]></Time>
<TimeTick>1651818366</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" Source="Action1 [GlobalDriver_Working]" SourceLine="155" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA[Test Information]]></Obj>
<Details ><![CDATA[datasheetused:VUE360_SMOKETESTSUITE.xlsServer Used:hpasstgaweb2]]></Details>
<Time><![CDATA[5/6/2022 - 2:26:06]]></Time>
<TimeTick>1651818366</TimeTick>
<NodeArgs eType="User" icon="7" nRep="13" Source="Action1 [GlobalDriver_Working]" SourceLine="167" >
<Disp><![CDATA[Test Information]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj ><![CDATA[Find Row No]]></Obj>
<Details ><![CDATA[Row No ofTC_002_VUE360 _Edit_MemberDemographics_Validateedited member details saved successfully:11]]></Details>
<Time><![CDATA[5/6/2022 - 2:26:13]]></Time>
<TimeTick>1651818373</TimeTick>
<NodeArgs eType="User" icon="7" nRep="14" status="Passed" Source="Action1 [GlobalDriver_Working]" SourceLine="456" >
<Disp><![CDATA[Find Row No]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj ><![CDATA[Find Row No]]></Obj>
<Details ><![CDATA[Row No ofTC_002_VUE360 _Edit_MemberDemographics_Validateedited member details saved successfully_END:59]]></Details>
<Time><![CDATA[5/6/2022 - 2:26:17]]></Time>
<TimeTick>1651818377</TimeTick>
<NodeArgs eType="User" icon="7" nRep="15" status="Passed" Source="Action1 [GlobalDriver_Working]" SourceLine="456" >
<Disp><![CDATA[Find Row No]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[Find Row No]]></Obj>
<Details ><![CDATA[Row No ofLOGOFF:5]]></Details>
<Time><![CDATA[5/6/2022 - 2:26:21]]></Time>
<TimeTick>1651818381</TimeTick>
<NodeArgs eType="User" icon="7" nRep="16" status="Passed" Source="Action1 [GlobalDriver_Working]" SourceLine="456" >
<Disp><![CDATA[Find Row No]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[Find Row No]]></Obj>
<Details ><![CDATA[Row No ofLOGOFF_END:10]]></Details>
<Time><![CDATA[5/6/2022 - 2:26:25]]></Time>
<TimeTick>1651818385</TimeTick>
<NodeArgs eType="User" icon="7" nRep="17" status="Passed" Source="Action1 [GlobalDriver_Working]" SourceLine="456" >
<Disp><![CDATA[Find Row No]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[5/6/2022 - 2:26:34]]></Time>
<TimeTick>1651818394</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[5/6/2022 - 2:26:34]]></Time>
<TimeTick>1651818394</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="20" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Brw_VUE360]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/6/2022 - 2:26:50]]></Time>
<TimeTick>1651818410</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Brw_VUE360.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/6/2022 - 2:26:50]]></Time>
<TimeTick>1651818410</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="23" >
<Disp><![CDATA[Brw_VUE360.Exist]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[2492384]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Pge_VUE360_SignIn]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/6/2022 - 2:26:50]]></Time>
<TimeTick>1651818410</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Edt_Uname.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/6/2022 - 2:26:50]]></Time>
<TimeTick>1651818410</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="26" >
<Disp><![CDATA[Edt_Uname.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Edt_Uname.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["MAPSHC\M91"]]></Details>
<Time><![CDATA[5/6/2022 - 2:26:50]]></Time>
<TimeTick>1651818410</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="29" >
<Disp><![CDATA[Edt_Uname.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Edt_Password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["615199fa2d774457381092a9eb8e78f073dd18e76ec09f98"]]></Details>
<Time><![CDATA[5/6/2022 - 2:26:54]]></Time>
<TimeTick>1651818414</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="32" >
<Disp><![CDATA[Edt_Password.SetSecure]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Btn_Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/6/2022 - 2:26:57]]></Time>
<TimeTick>1651818417</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="35" >
<Disp><![CDATA[Btn_Submit.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf7.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="25" >
<Disp><![CDATA[Pge_VUE360_SignIn]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="22" >
<Disp><![CDATA[Brw_VUE360]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[2492384]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA[Launched application and logged in]]></Obj>
<Details ><![CDATA[Application launched successfully:http://blsstgaweb1.stga.mapshc.com/VUE360]]></Details>
<Time><![CDATA[5/6/2022 - 2:26:57]]></Time>
<TimeTick>1651818417</TimeTick>
<NodeArgs eType="User" icon="7" nRep="36" status="Passed" >
<Disp><![CDATA[Launched application and logged in]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    1]]></Details>
<Time><![CDATA[5/6/2022 - 2:26:57]]></Time>
<TimeTick>1651818417</TimeTick>
<NodeArgs eType="User" icon="7" nRep="37" Source="Action1 [GlobalDriver_Working]" SourceLine="1572" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    2,Value used:7]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:06]]></Time>
<TimeTick>1651818426</TimeTick>
<NodeArgs eType="User" icon="7" nRep="38" Source="Action1 [GlobalDriver_Working]" SourceLine="1574" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[Skip row]]></Obj>
<Details ><![CDATA[You have successfully skipped the row no 1]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:06]]></Time>
<TimeTick>1651818426</TimeTick>
<NodeArgs eType="User" icon="7" nRep="39" Source="Action1 [GlobalDriver_Working]" SourceLine="563" >
<Disp><![CDATA[Skip row]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Brw_VUE360]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:08]]></Time>
<TimeTick>1651818428</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Pge_VUE360_Member]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:09]]></Time>
<TimeTick>1651818429</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Lnk_Member.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:09]]></Time>
<TimeTick>1651818429</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="43" >
<Disp><![CDATA[Lnk_Member.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf10.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="42" >
<Disp><![CDATA[Pge_VUE360_Member]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf9.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="41" >
<Disp><![CDATA[Brw_VUE360]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf8.xml]]></Path>
<ASHilite><![CDATA[2492384]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj ><![CDATA[Member]]></Obj>
<Details ><![CDATA[Succeded at Row No:    11]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:09]]></Time>
<TimeTick>1651818429</TimeTick>
<NodeArgs eType="User" icon="7" nRep="44" Source="Action1 [GlobalDriver_Working]" SourceLine="1572" >
<Disp><![CDATA[Member]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Brw_VUE360]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:10]]></Time>
<TimeTick>1651818430</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Pge_VUE360_Member]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:10]]></Time>
<TimeTick>1651818430</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Lnk_Member.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:10]]></Time>
<TimeTick>1651818430</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="48" >
<Disp><![CDATA[Lnk_Member.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf13.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Lnk_Member.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:10]]></Time>
<TimeTick>1651818430</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="51" >
<Disp><![CDATA[Lnk_Member.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf14.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="47" >
<Disp><![CDATA[Pge_VUE360_Member]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf12.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="46" >
<Disp><![CDATA[Brw_VUE360]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf11.xml]]></Path>
<ASHilite><![CDATA[2492384]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA[Member]]></Obj>
<Details ><![CDATA[Succeded at Row No:    12]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:11]]></Time>
<TimeTick>1651818431</TimeTick>
<NodeArgs eType="User" icon="7" nRep="52" Source="Action1 [GlobalDriver_Working]" SourceLine="1572" >
<Disp><![CDATA[Member]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Brw_VUE360]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:13]]></Time>
<TimeTick>1651818433</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Pge_VUE360_MemberSearch]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:13]]></Time>
<TimeTick>1651818433</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Edt_MemberID.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:13]]></Time>
<TimeTick>1651818433</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="56" >
<Disp><![CDATA[Edt_MemberID.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf17.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="55" >
<Disp><![CDATA[Pge_VUE360_MemberSearch]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf16.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="54" >
<Disp><![CDATA[Brw_VUE360]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf15.xml]]></Path>
<ASHilite><![CDATA[2492384]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj ><![CDATA[MemberID]]></Obj>
<Details ><![CDATA[Succeded at Row No:    13]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:13]]></Time>
<TimeTick>1651818433</TimeTick>
<NodeArgs eType="User" icon="7" nRep="57" Source="Action1 [GlobalDriver_Working]" SourceLine="1572" >
<Disp><![CDATA[MemberID]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Brw_VUE360]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:15]]></Time>
<TimeTick>1651818435</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Pge_VUE360_MemberSearch]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:15]]></Time>
<TimeTick>1651818435</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Edt_MemberID.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:15]]></Time>
<TimeTick>1651818435</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="61" >
<Disp><![CDATA[Edt_MemberID.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf20.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Edt_MemberID.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["7X1088888803"]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:15]]></Time>
<TimeTick>1651818435</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="64" >
<Disp><![CDATA[Edt_MemberID.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf21.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="60" >
<Disp><![CDATA[Pge_VUE360_MemberSearch]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf19.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="59" >
<Disp><![CDATA[Brw_VUE360]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf18.xml]]></Path>
<ASHilite><![CDATA[2492384]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj ><![CDATA[MemberID]]></Obj>
<Details ><![CDATA[Succeded at Row No:    14,Value used:7X1088888803]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:15]]></Time>
<TimeTick>1651818435</TimeTick>
<NodeArgs eType="User" icon="7" nRep="65" Source="Action1 [GlobalDriver_Working]" SourceLine="1574" >
<Disp><![CDATA[MemberID]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    15,Value used:VUE360]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:23]]></Time>
<TimeTick>1651818443</TimeTick>
<NodeArgs eType="User" icon="7" nRep="66" Source="Action1 [GlobalDriver_Working]" SourceLine="1574" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Brw_VUE360]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:24]]></Time>
<TimeTick>1651818444</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Pge_VUE360_MemberSearch]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:24]]></Time>
<TimeTick>1651818444</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Pge_VUE360_MemberSearch.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:25]]></Time>
<TimeTick>1651818445</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="70" >
<Disp><![CDATA[Pge_VUE360_MemberSearch.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf24.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Btn_Submit.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:25]]></Time>
<TimeTick>1651818445</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="71" >
<Disp><![CDATA[Btn_Submit.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf25.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Btn_Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:27]]></Time>
<TimeTick>1651818447</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="75" >
<Disp><![CDATA[Btn_Submit.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf26.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="69" >
<Disp><![CDATA[Pge_VUE360_MemberSearch]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf23.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="68" >
<Disp><![CDATA[Brw_VUE360]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf22.xml]]></Path>
<ASHilite><![CDATA[2492384]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj ><![CDATA[Submit]]></Obj>
<Details ><![CDATA[Succeded at Row No:    16]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:29]]></Time>
<TimeTick>1651818449</TimeTick>
<NodeArgs eType="User" icon="7" nRep="76" Source="Action1 [GlobalDriver_Working]" SourceLine="1572" >
<Disp><![CDATA[Submit]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    17,Value used:3]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:33]]></Time>
<TimeTick>1651818453</TimeTick>
<NodeArgs eType="User" icon="7" nRep="77" Source="Action1 [GlobalDriver_Working]" SourceLine="1574" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Brw_VUE360]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:34]]></Time>
<TimeTick>1651818454</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Pge_VUE360_MemberTabs]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:34]]></Time>
<TimeTick>1651818454</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Ele_Summary.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:34]]></Time>
<TimeTick>1651818454</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="81" >
<Disp><![CDATA[Ele_Summary.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf29.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Ele_Summary.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:35]]></Time>
<TimeTick>1651818455</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="84" >
<Disp><![CDATA[Ele_Summary.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf30.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="80" >
<Disp><![CDATA[Pge_VUE360_MemberTabs]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf28.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="79" >
<Disp><![CDATA[Brw_VUE360]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf27.xml]]></Path>
<ASHilite><![CDATA[2492384]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj ><![CDATA[Summary]]></Obj>
<Details ><![CDATA[Succeded at Row No:    18]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:35]]></Time>
<TimeTick>1651818455</TimeTick>
<NodeArgs eType="User" icon="7" nRep="85" Source="Action1 [GlobalDriver_Working]" SourceLine="1572" >
<Disp><![CDATA[Summary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    19,Value used:3]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:39]]></Time>
<TimeTick>1651818459</TimeTick>
<NodeArgs eType="User" icon="7" nRep="86" Source="Action1 [GlobalDriver_Working]" SourceLine="1574" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    20,Value used:VUE360]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:46]]></Time>
<TimeTick>1651818466</TimeTick>
<NodeArgs eType="User" icon="7" nRep="87" Source="Action1 [GlobalDriver_Working]" SourceLine="1574" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Brw_VUE360]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:47]]></Time>
<TimeTick>1651818467</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Pge_VUE360_MemberTabs]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/6/2022 - 2:27:47]]></Time>
<TimeTick>1651818467</TimeTick>
<Step rID="T63">