<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.1" os="" host="BLSSTGATST2"><DocLocation><![CDATA[H:\HPA_Test\Test Resources_VUE360\Scripts\VUE360 Smoke Test\TC_01_VUE360_REGRESSIONTESTSUITE]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[TC_01_VUE360_REGRESSIONTESTSUITE]]></DName>
<Res><![CDATA[Report35]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Action rID="T5">
<AName><![CDATA[Action1 [GlobalDriver_Working_old - Copy]]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[5/10/2022 - 2:37:41]]></Time>
<TimeTick>1652164661</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="9" status="Passed" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="151" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[5/10/2022 - 2:37:43]]></Time>
<TimeTick>1652164663</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="10" status="Passed" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="153" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[5/10/2022 - 2:37:43]]></Time>
<TimeTick>1652164663</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="11" status="Passed" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="154" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[5/10/2022 - 2:37:43]]></Time>
<TimeTick>1652164663</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="155" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA[Test Information]]></Obj>
<Details ><![CDATA[datasheetused:VUE360_REGRESSIONSUITE.xlsServer Used:hpasstgaweb2]]></Details>
<Time><![CDATA[5/10/2022 - 2:37:44]]></Time>
<TimeTick>1652164664</TimeTick>
<NodeArgs eType="User" icon="7" nRep="13" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="167" >
<Disp><![CDATA[Test Information]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj ><![CDATA[Find Row No]]></Obj>
<Details ><![CDATA[Row No ofTC_REG_001_VUE360 _ConfigurationView_Rules _ValidatetheSearchandViewpagefunctionalities:10]]></Details>
<Time><![CDATA[5/10/2022 - 2:38:04]]></Time>
<TimeTick>1652164684</TimeTick>
<NodeArgs eType="User" icon="7" nRep="14" status="Passed" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="456" >
<Disp><![CDATA[Find Row No]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj ><![CDATA[Find Row No]]></Obj>
<Details ><![CDATA[Row No ofTC_REG_001_VUE360 _ConfigurationView_Rules _ValidatetheSearchandViewpagefunctionalities_END:99]]></Details>
<Time><![CDATA[5/10/2022 - 2:38:19]]></Time>
<TimeTick>1652164699</TimeTick>
<NodeArgs eType="User" icon="7" nRep="15" status="Passed" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="456" >
<Disp><![CDATA[Find Row No]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[Find Row No]]></Obj>
<Details ><![CDATA[Row No ofLOGOFF:4]]></Details>
<Time><![CDATA[5/10/2022 - 2:38:35]]></Time>
<TimeTick>1652164715</TimeTick>
<NodeArgs eType="User" icon="7" nRep="16" status="Passed" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="456" >
<Disp><![CDATA[Find Row No]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[Find Row No]]></Obj>
<Details ><![CDATA[Row No ofLOGOFF_END:9]]></Details>
<Time><![CDATA[5/10/2022 - 2:38:50]]></Time>
<TimeTick>1652164730</TimeTick>
<NodeArgs eType="User" icon="7" nRep="17" status="Passed" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="456" >
<Disp><![CDATA[Find Row No]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[5/10/2022 - 2:38:56]]></Time>
<TimeTick>1652164736</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[5/10/2022 - 2:38:56]]></Time>
<TimeTick>1652164736</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="20" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Brw_VUE360]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:12]]></Time>
<TimeTick>1652164752</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Brw_VUE360.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:12]]></Time>
<TimeTick>1652164752</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="23" >
<Disp><![CDATA[Brw_VUE360.Exist]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[34866084]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Pge_VUE360_SignIn]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:12]]></Time>
<TimeTick>1652164752</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Edt_Uname.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:12]]></Time>
<TimeTick>1652164752</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="26" >
<Disp><![CDATA[Edt_Uname.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Edt_Uname.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["MAPSHC\M91"]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:12]]></Time>
<TimeTick>1652164752</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="29" >
<Disp><![CDATA[Edt_Uname.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Edt_Password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["615199fa2d774457381092a9eb8e78f073dd18e76ec09f98"]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:16]]></Time>
<TimeTick>1652164756</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="32" >
<Disp><![CDATA[Edt_Password.SetSecure]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Btn_Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:19]]></Time>
<TimeTick>1652164759</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="35" >
<Disp><![CDATA[Btn_Submit.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf7.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="25" >
<Disp><![CDATA[Pge_VUE360_SignIn]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="22" >
<Disp><![CDATA[Brw_VUE360]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[34866084]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA[Launched application and logged in]]></Obj>
<Details ><![CDATA[Application launched successfully:http://blsstgaweb1.stga.mapshc.com/VUE360]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:19]]></Time>
<TimeTick>1652164759</TimeTick>
<NodeArgs eType="User" icon="7" nRep="36" status="Passed" >
<Disp><![CDATA[Launched application and logged in]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    1]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:19]]></Time>
<TimeTick>1652164759</TimeTick>
<NodeArgs eType="User" icon="7" nRep="37" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="1625" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    2,Value used:10]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:30]]></Time>
<TimeTick>1652164770</TimeTick>
<NodeArgs eType="User" icon="7" nRep="38" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="1627" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[COMMON_VERIFICATION:Q_I_VALIDATE_WEBELEMENT]]></Obj>
<Details ><![CDATA[WebElement  :innertext=Configuration View matches with expected value Configuration View]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:31]]></Time>
<TimeTick>1652164771</TimeTick>
<NodeArgs eType="User" icon="7" nRep="40" status="Passed" >
<Disp><![CDATA[COMMON_VERIFICATION:Q_I_VALIDATE_WEBELEMENT]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[ConfigurationView]]></Obj>
<Details ><![CDATA[Succeded at Row No:    10,Value used:Configuration View]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:31]]></Time>
<TimeTick>1652164771</TimeTick>
<NodeArgs eType="User" icon="7" nRep="41" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="1627" >
<Disp><![CDATA[ConfigurationView]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Brw_VUE360]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:32]]></Time>
<TimeTick>1652164772</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Pge_VUE360_MemberSearch]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:32]]></Time>
<TimeTick>1652164772</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Ele_ConfigurationView.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:32]]></Time>
<TimeTick>1652164772</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="45" >
<Disp><![CDATA[Ele_ConfigurationView.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf10.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Ele_ConfigurationView.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:32]]></Time>
<TimeTick>1652164772</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="48" >
<Disp><![CDATA[Ele_ConfigurationView.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf11.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="44" >
<Disp><![CDATA[Pge_VUE360_MemberSearch]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf9.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="43" >
<Disp><![CDATA[Brw_VUE360]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf8.xml]]></Path>
<ASHilite><![CDATA[34866084]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj ><![CDATA[ConfigurationView]]></Obj>
<Details ><![CDATA[Succeded at Row No:    11]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:33]]></Time>
<TimeTick>1652164773</TimeTick>
<NodeArgs eType="User" icon="7" nRep="49" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="1625" >
<Disp><![CDATA[ConfigurationView]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj ><![CDATA[COMMON_VERIFICATION:Q_I_VALIDATE_WEBELEMENT]]></Obj>
<Details ><![CDATA[WebElement  :innertext=Configuration matches with expected value Configuration]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:34]]></Time>
<TimeTick>1652164774</TimeTick>
<NodeArgs eType="User" icon="7" nRep="51" status="Passed" >
<Disp><![CDATA[COMMON_VERIFICATION:Q_I_VALIDATE_WEBELEMENT]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA[ConfigurationText]]></Obj>
<Details ><![CDATA[Succeded at Row No:    12,Value used:Configuration]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:34]]></Time>
<TimeTick>1652164774</TimeTick>
<NodeArgs eType="User" icon="7" nRep="52" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="1627" >
<Disp><![CDATA[ConfigurationText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA[COMMON_VERIFICATION:Q_I_VALIDATE_WEBELEMENT]]></Obj>
<Details ><![CDATA[WebElement  :innertext=Program matches with expected value Program]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:34]]></Time>
<TimeTick>1652164774</TimeTick>
<NodeArgs eType="User" icon="7" nRep="54" status="Passed" >
<Disp><![CDATA[COMMON_VERIFICATION:Q_I_VALIDATE_WEBELEMENT]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj ><![CDATA[ProgramTab]]></Obj>
<Details ><![CDATA[Succeded at Row No:    13,Value used:Program]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:35]]></Time>
<TimeTick>1652164775</TimeTick>
<NodeArgs eType="User" icon="7" nRep="55" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="1627" >
<Disp><![CDATA[ProgramTab]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj ><![CDATA[COMMON_VERIFICATION:Q_I_VALIDATE_WEBELEMENT]]></Obj>
<Details ><![CDATA[WebElement  :innertext=Reference Codes matches with expected value Reference Codes]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:35]]></Time>
<TimeTick>1652164775</TimeTick>
<NodeArgs eType="User" icon="7" nRep="57" status="Passed" >
<Disp><![CDATA[COMMON_VERIFICATION:Q_I_VALIDATE_WEBELEMENT]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj ><![CDATA[ReferenceCodes]]></Obj>
<Details ><![CDATA[Succeded at Row No:    14,Value used:Reference Codes]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:36]]></Time>
<TimeTick>1652164776</TimeTick>
<NodeArgs eType="User" icon="7" nRep="58" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="1627" >
<Disp><![CDATA[ReferenceCodes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Brw_VUE360]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:36]]></Time>
<TimeTick>1652164776</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Pge_VUE360_ConfigurationView]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:36]]></Time>
<TimeTick>1652164776</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Ele_ReferenceCodes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:36]]></Time>
<TimeTick>1652164776</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="62" >
<Disp><![CDATA[Ele_ReferenceCodes.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf14.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Ele_ReferenceCodes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:37]]></Time>
<TimeTick>1652164777</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="65" >
<Disp><![CDATA[Ele_ReferenceCodes.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf15.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="61" >
<Disp><![CDATA[Pge_VUE360_ConfigurationView]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf13.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="60" >
<Disp><![CDATA[Brw_VUE360]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf12.xml]]></Path>
<ASHilite><![CDATA[34866084]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[ReferenceCodes]]></Obj>
<Details ><![CDATA[Succeded at Row No:    15]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:37]]></Time>
<TimeTick>1652164777</TimeTick>
<NodeArgs eType="User" icon="7" nRep="66" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="1625" >
<Disp><![CDATA[ReferenceCodes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    16,Value used:VUE 360]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:46]]></Time>
<TimeTick>1652164786</TimeTick>
<NodeArgs eType="User" icon="7" nRep="67" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="1627" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Brw_VUE360]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:47]]></Time>
<TimeTick>1652164787</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Pge_VUE360_ConfigurationView]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:47]]></Time>
<TimeTick>1652164787</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Ele_ServiceCodeSearch.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:47]]></Time>
<TimeTick>1652164787</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="71" >
<Disp><![CDATA[Ele_ServiceCodeSearch.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf18.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Ele_ServiceCodeSearch.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:47]]></Time>
<TimeTick>1652164787</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="73" >
<Disp><![CDATA[Ele_ServiceCodeSearch.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf19.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Edt_CPTCode.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:48]]></Time>
<TimeTick>1652164788</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="75" >
<Disp><![CDATA[Edt_CPTCode.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf20.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Edt_CPTCode.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["00102"]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:48]]></Time>
<TimeTick>1652164788</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="78" >
<Disp><![CDATA[Edt_CPTCode.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf21.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="70" >
<Disp><![CDATA[Pge_VUE360_ConfigurationView]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf17.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="69" >
<Disp><![CDATA[Brw_VUE360]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf16.xml]]></Path>
<ASHilite><![CDATA[34866084]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj ><![CDATA[CPTCode]]></Obj>
<Details ><![CDATA[Succeded at Row No:    18,Value used:00102]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:48]]></Time>
<TimeTick>1652164788</TimeTick>
<NodeArgs eType="User" icon="7" nRep="79" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="1627" >
<Disp><![CDATA[CPTCode]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    19,Value used:3]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:52]]></Time>
<TimeTick>1652164792</TimeTick>
<NodeArgs eType="User" icon="7" nRep="80" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="1627" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Brw_VUE360]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:53]]></Time>
<TimeTick>1652164793</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Pge_VUE360_ConfigurationView]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:53]]></Time>
<TimeTick>1652164793</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Pge_VUE360_ConfigurationView.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:53]]></Time>
<TimeTick>1652164793</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="84" >
<Disp><![CDATA[Pge_VUE360_ConfigurationView.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf24.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Btn_Search.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:53]]></Time>
<TimeTick>1652164793</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="85" >
<Disp><![CDATA[Btn_Search.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf25.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Btn_Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:55]]></Time>
<TimeTick>1652164795</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="89" >
<Disp><![CDATA[Btn_Search.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf26.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="83" >
<Disp><![CDATA[Pge_VUE360_ConfigurationView]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf23.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="82" >
<Disp><![CDATA[Brw_VUE360]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf22.xml]]></Path>
<ASHilite><![CDATA[34866084]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj ><![CDATA[Search]]></Obj>
<Details ><![CDATA[Succeded at Row No:    20]]></Details>
<Time><![CDATA[5/10/2022 - 2:39:58]]></Time>
<TimeTick>1652164798</TimeTick>
<NodeArgs eType="User" icon="7" nRep="90" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="1625" >
<Disp><![CDATA[Search]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj ><![CDATA[NA]]></Obj>
<Details ><![CDATA[Succeded at Row No:    21,Value used:VUE 360]]></Details>
<Time><![CDATA[5/10/2022 - 2:40:04]]></Time>
<TimeTick>1652164804</TimeTick>
<NodeArgs eType="User" icon="7" nRep="91" Source="Action1 [GlobalDriver_Working_old - Copy]" SourceLine="1627" >
<Disp><![CDATA[NA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj ><![CDATA[COMMON_VERIFICATION:Q_I_VALIDATE_WEBELEMENT]]></Obj>
<Details ><![CDATA[WebElement  :innertext=00102 matches with expected value 00102]]></Details>